spring:
  application:
    name: E-Commerce-SpringBoot
  datasource:
    url: jdbc:mysql://localhost:3306/Ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

server:
  port: 8080


security:
  jwt:
    expirationInMils: 604800000
    secret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
